version: "3.9"

x-mapserver-image: &mapserver-image pdok/mapserver:7.6.4-patch5-3-buster-lighttpd
x-mapproxy-image: &mapproxy-image pdok/mapproxy:1.13.2-patched-2

services:

  mapserver:
    image: *mapserver-image
    container_name: "mapserver"
    # ports:
    #   - 80:80
    restart: unless-stopped
    environment:
        MS_MAPFILE: /srv/config/administrative-boundaries.map
    volumes:
      - ./config/mapserver:/srv/config
      - ./data:/srv/data
    networks:
      nsdi:

  mapproxy:
    image: *mapproxy-image
    container_name: "mapproxy"
    restart: unless-stopped
    environment:
        AWS_ACCESS_KEY_ID: minio
        AWS_SECRET_ACCESS_KEY: minio123
    ports:
      - 80:80
    volumes:
      - ./config/mapproxy-minio:/srv/mapproxy/config
    networks:
      nsdi:

  minio:
    image: minio/minio
    container_name: "minio"
    ports:
      - 9001:9001    
    # volumes:
    #   - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      nsdi:

networks:
  nsdi:      
